name: shel commands
on: [push,pull_request]
jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello Workd from yash-github-actions"
      - name: multiline script
        run: |
          node -v
          npm -v