name: runpy
on: [push]
jobs: 
  runpy:
    runs-on: ubuntu-latest
    steps: 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute my script
        run: |
          python --version
      - name: install beautiful soup
        run: |
          pip3 install beautifulsoup4
